/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/t523a3jDKgI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function new() {
  return (
    <div
      className="min-h-screen bg-cover bg-center"
      style={{ backgroundImage: "url('/path/to/your/background-image.jpg')" }}
    >
      <header className="flex items-center justify-between p-6">
        <div className="flex items-center space-x-2">
          <LogInIcon className="w-6 h-6" />
          <span className="text-lg font-semibold">CreativeSolutions</span>
        </div>
        <nav className="flex space-x-6">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Link href="#" className="text-sm font-medium" prefetch={false}>
                <ChevronLeftIcon className="w-4 h-4 mr-1" />
                Services
              </Link>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start">
              <DropdownMenuItem>
                <Link href="#" className="block px-4 py-2 text-sm hover:bg-muted" prefetch={false}>
                  Pages
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Link href="#" className="block px-4 py-2 text-sm hover:bg-muted" prefetch={false}>
                  Mia
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Link href="#" className="block px-4 py-2 text-sm hover:bg-muted" prefetch={false}>
                  Products
                </Link>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Link href="#" className="block px-4 py-2 text-sm hover:bg-muted" prefetch={false}>
                  Juned
                </Link>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <Link href="#" className="text-sm font-medium" prefetch={false}>
            Portfolio
          </Link>
          <Link href="#" className="text-sm font-medium" prefetch={false}>
            Pricing
          </Link>
          <Link href="#" className="text-sm font-medium" prefetch={false}>
            Contact
          </Link>
          <MoonIcon className="w-6 h-6" />
        </nav>
      </header>
      <main className="flex flex-col items-center justify-center flex-1 text-center">
        <h1 className="text-5xl font-bold">Welcome to CreativeSolutions</h1>
        <p className="mt-4 text-lg text-muted-foreground">
          Your one-stop shop for graphic design, printing, branding, and digital marketing solutions.
        </p>
        <div className="mt-6 space-x-4">
          <Button className="bg-black text-white">Get Started</Button>
          <Button variant="outline">Learn More</Button>
        </div>
      </main>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}


function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}
